/**
 * The complete set of artifacts an install owns.
 *
 * One definition, used by every command: `init` writes it, `check` compares
 * against it, `upgrade` re-renders it, `eject` removes it. If this list ever
 * disagreed with itself between commands, `check` would report drift that
 * `upgrade` could not fix — so there is exactly one.
 */

import { readFile, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { generate as generateAuthoritySplit } from './authority-split.js'
import { generate as generateCloseOut } from './close-out.js'

const HERE = dirname(fileURLToPath(import.meta.url))
export const TEMPLATE_ROOT = join(HERE, '../../templates')
export const RUNTIME_ROOT = join(HERE, '../../runtime')

/** Every .md under templates/<sub>, relative to that directory. */
export async function templateFiles(sub) {
  const base = join(TEMPLATE_ROOT, sub)
  const out = []
  let entries
  try {
    entries = await readdir(base, { withFileTypes: true, recursive: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue
    const abs = join(entry.parentPath ?? entry.path, entry.name)
    out.push(abs.slice(base.length + 1))
  }
  return out.sort()
}

/** Which agent files this project already uses; CLAUDE.md if none. */
export function pointerTargets(detected) {
  const a = detected?.agentConfig || {}
  const targets = []
  if (a.claudeMd) targets.push('CLAUDE.md')
  if (a.agentsMd) targets.push('AGENTS.md')
  return targets.length ? targets : ['CLAUDE.md']
}

export function pointerBody() {
  return [
    '## How work is done here',
    '',
    'Read these before planning or editing. They are the authority; this block is a pointer.',
    '',
    '- `docs/authority-split.md` — what you can and cannot verify here. Read it first.',
    '- `docs/rules/active/` — case law. At session start, scan it and load every rule whose',
    '  Trigger matches this turn. Rules are trigger-scoped, never ambient.',
    '- `docs/close-out.md` — end a working session with this, including its rule-proposals line.',
    '',
    'At any catch with a proven root cause, draft a rule: `harness rule propose "<name>"`.',
    'You draft; you never ratify. Only a human moves a rule into active/.',
    '',
    'Generated by harness. Edit `.harness/answers.json` and re-run, not this block.',
  ].join('\n')
}

/**
 * PreToolUse blocks a bad write before it lands; PostToolUse runs the checks
 * that need the finished file. Both invoke the VENDORED runner, so the hooks
 * keep working with this CLI uninstalled.
 */
export function claudeHookSettings() {
  const cmd = (mode) =>
    `node "$CLAUDE_PROJECT_DIR/.harness/bin/gate.mjs" --mode ${mode} --host claude --root "$CLAUDE_PROJECT_DIR"`
  const entry = (mode) => ({
    matcher: 'Edit|Write|MultiEdit',
    hooks: [{ type: 'command', command: cmd(mode), timeout: 30 }],
  })
  return { hooks: { PreToolUse: [entry('pre')], PostToolUse: [entry('post')] } }
}

export const EMPTY_GATES = {
  version: 1,
  $comment:
    'Empty on purpose. Gates are created by `harness rule promote <name>`, from a rule that earned one. See docs/rules/README.md.',
  gates: [],
}

/**
 * @param {{doc: object, detected: object}} input
 * @returns {Promise<Array<{path:string, kind:'file'|'block', body:string, blockId?:string, version?:number}>>}
 */
export async function buildArtifacts({ doc, detected }) {
  const out = []

  const authority = await generateAuthoritySplit({
    answers: doc.answers,
    detected,
    projectName: doc.project?.name,
    now: doc.generatedAt ? new Date(doc.generatedAt) : undefined,
  })
  out.push({ path: 'docs/authority-split.md', kind: 'file', body: authority.content })

  const closeOut = await generateCloseOut({
    answers: doc.answers, detected, projectName: doc.project?.name,
  })
  out.push({ path: 'docs/close-out.md', kind: 'file', body: closeOut.content })

  // Case-law scaffolding ships verbatim: machinery, never content.
  for (const rel of await templateFiles('rules')) {
    out.push({
      path: join('docs/rules', rel),
      kind: 'file',
      body: await readFile(join(TEMPLATE_ROOT, 'rules', rel), 'utf8'),
    })
  }

  const targets = pointerTargets(detected)
  for (const target of targets) {
    out.push({ path: target, kind: 'block', blockId: 'pointer', body: pointerBody(), version: 1 })
  }

  out.push({
    path: '.harness/bin/gate.mjs', kind: 'file',
    body: await readFile(join(RUNTIME_ROOT, 'gate.mjs'), 'utf8'),
  })
  out.push({
    path: '.harness/schema/gates.schema.json', kind: 'file',
    body: await readFile(join(RUNTIME_ROOT, 'schema/gates.schema.json'), 'utf8'),
  })
  out.push({
    path: '.harness/gates.json', kind: 'file',
    body: JSON.stringify(EMPTY_GATES, null, 2) + '\n',
  })

  if (targets.includes('CLAUDE.md')) {
    out.push({
      path: '.claude/settings.json', kind: 'file',
      body: JSON.stringify(claudeHookSettings(), null, 2) + '\n',
    })
    for (const rel of await templateFiles('adapters/claude/commands')) {
      out.push({
        path: join('.claude/commands', rel), kind: 'file',
        body: await readFile(join(TEMPLATE_ROOT, 'adapters/claude/commands', rel), 'utf8'),
      })
    }
  }

  out.push({
    path: '.gitignore', kind: 'block', blockId: 'harness', version: 1,
    body: ['# Local gate telemetry — per-machine, never committed.', '.harness/gate-fires.jsonl'].join('\n'),
  })

  return out
}
