/**
 * Adapters — one doctrine, many agent tools.
 *
 * The doctrine lives once, in `docs/`. Every agent tool gets a small POINTER
 * telling it what to read and when. That is the whole design: a tool-specific
 * file never contains doctrine, so there is nothing to drift.
 *
 * Two rules learned from watching a large competitor get this wrong:
 *
 *  1. **Declared support must not outrun tested support.** A tool counts as
 *     supported only when a golden-render test covers it. Their README claimed
 *     full support for ten hosts and had fixtures for three; the other seven
 *     had open issues saying setup was broken.
 *
 *  2. **Never shadow a host's built-in command.** They shipped a `/review`
 *     command that silently took precedence over the host's own. Generated
 *     command names are checked against a per-host reserved list, and a
 *     collision is an error rather than a surprise six weeks later.
 */

/**
 * Command names each host already owns. Generating one of these would shadow
 * the host's built-in, and the user would never be told why it changed.
 */
export const RESERVED_COMMANDS = {
  'claude-code': [
    'init', 'help', 'clear', 'compact', 'config', 'doctor', 'memory', 'model',
    'permissions', 'review', 'rewind', 'context', 'cost', 'login', 'logout',
    'status', 'agents', 'hooks', 'mcp', 'resume', 'export', 'vim', 'terminal-setup',
  ],
  cursor: ['new', 'edit', 'chat', 'help'],
  copilot: ['explain', 'fix', 'tests', 'help', 'doc'],
  'agents-md': [],
}

/** The pointer body every adapter renders in its own idiom. */
export function pointerLines() {
  return [
    { text: '`docs/authority-split.md` — what you can and cannot verify here. Read it first.' },
    { text: '`docs/rules/active/` — case law. At session start, scan it and load every rule whose Trigger matches this turn. Rules are trigger-scoped, never ambient.' },
    { text: '`docs/close-out.md` — end a working session with this, including its rule-proposals line.' },
  ]
}

const PROPOSE_NOTE =
  'At any catch with a proven root cause, draft a rule: `harness rule propose "<name>"`. ' +
  'You draft; you never ratify. Only a human moves a rule into active/.'

const GENERATED_NOTE = 'Generated by harness. Edit `.harness/answers.json` and re-run, not this block.'

/**
 * @typedef {{id: string, label: string, detect: (d: object) => boolean,
 *            artifacts: (ctx: object) => Array<object>, tested: boolean}} Adapter
 */

/** @type {Adapter[]} */
export const ADAPTERS = [
  {
    id: 'claude-code',
    label: 'Claude Code',
    tested: true,
    detect: (d) => Boolean(d?.agentConfig?.claudeMd || d?.agentConfig?.claudeDir),
    artifacts() {
      return [{ path: 'CLAUDE.md', kind: 'block', blockId: 'pointer', version: 1, body: markdownPointer() }]
    },
  },
  {
    id: 'agents-md',
    label: 'AGENTS.md (Codex and others)',
    tested: true,
    detect: (d) => Boolean(d?.agentConfig?.agentsMd),
    artifacts() {
      return [{ path: 'AGENTS.md', kind: 'block', blockId: 'pointer', version: 1, body: markdownPointer() }]
    },
  },
  {
    id: 'cursor',
    label: 'Cursor',
    tested: true,
    detect: (d) => Boolean(d?.agentConfig?.cursorRules),
    artifacts() {
      // Cursor reads .mdc rule files with YAML frontmatter. alwaysApply keeps
      // the pointer in context; the doctrine itself still lives in docs/.
      const body = [
        '---',
        'description: Where this project keeps its engineering doctrine',
        'alwaysApply: true',
        '---',
        '',
        markdownPointer(),
      ].join('\n')
      return [{ path: '.cursor/rules/harness.mdc', kind: 'file', body: body + '\n' }]
    },
  },
  {
    id: 'copilot',
    label: 'GitHub Copilot',
    tested: true,
    detect: (d) => Boolean(d?.agentConfig?.copilot),
    artifacts() {
      return [{
        path: '.github/copilot-instructions.md',
        kind: 'block', blockId: 'pointer', version: 1, body: markdownPointer(),
      }]
    },
  },
]

function markdownPointer() {
  return [
    '## How work is done here',
    '',
    'Read these before planning or editing. They are the authority; this block is a pointer.',
    '',
    ...pointerLines().map((l) => `- ${l.text}`),
    '',
    PROPOSE_NOTE,
    '',
    GENERATED_NOTE,
  ].join('\n')
}

/**
 * Which adapters apply to this project.
 *
 * Writing a Cursor rule file into a repo that has never seen Cursor is
 * clutter, and clutter is how a harness gets deleted. Default to Claude Code
 * only when nothing at all is detected — one file beats none, and it is the
 * host this was built against.
 */
export function selectAdapters(detected, { only = null } = {}) {
  if (only) return ADAPTERS.filter((a) => only.includes(a.id))
  const found = ADAPTERS.filter((a) => a.detect(detected))
  return found.length ? found : ADAPTERS.filter((a) => a.id === 'claude-code')
}

export function getAdapter(id) {
  return ADAPTERS.find((a) => a.id === id) ?? null
}

/**
 * Would any generated command shadow a host built-in?
 * Returns the collisions; an empty array means safe.
 */
export function commandCollisions(hostId, commandNames) {
  const reserved = new Set(RESERVED_COMMANDS[hostId] ?? [])
  return commandNames
    .map((n) => String(n).replace(/\.md$/, '').replace(/^\//, ''))
    .filter((n) => reserved.has(n))
}
